version: '3.5'

services:
  thumbnail-generator:
    build:
      dockerfile: Dockerfile.local
      context: ../../
    volumes:
      - ../../src:/app/
    working_dir: /app
    tty : true
    ports:
      - 3000:3000
  minio:
    image: minio/minio
    volumes:
      - ./minio-data:/data
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=thumbnail-gen
      - MINIO_ROOT_PASSWORD=488c6&caaaAC
    command: server /data --console-address ":8080"
