FROM golang:1.17.0-bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y --no-install-recommends \
    tzdata ca-certificates build-essential git curl wget \
    libvips-dev libvips-tools

ENV PATH "$PATH:/usr/local/go/bin"

RUN mkdir /app

WORKDIR /app